### ISSUE TITLE
[Feature Request] Protect certain tweets

### ISSUE THREAD

**Issue by rtgibbons** [christophercliff/tweet-lifetime#2]
Sometimes it might be beneficial to leave tweet alone, being able to provide the ID of the tweet so it won't get deleted would be beneficial.

I'm thinking of storing an array of IDs or a text file of one per line?

**Comment by christophercliff** [comment]
The `IGNORE_HASHTAG` config is meant to solve this problem https://github.com/christophercliff/tweet-lifetime/blob/fe1ae545d927dc0e2954f6fe02b512423d86d33a/app.json#L20-L23.

In the default case tweets contains the hashtag "#pin" won't be deleted.

**Comment by rtgibbons** [comment]
I forgot about that completely, just tested with Keybase looking for the new tweet, and it found it even with the hashtag - thanks.
